export const USERTYPE = {

  ACCOUNTANT: [
    "CAN_OPEN_DEDICATED_VIRTUAL_BANK_ACCOUNT",
    "SHOULD_HAVE_WALLET_TO_WALLET_BY_DEFAULT",
    "SHOULD_BE_ABLE_TO_PERFORM_WALLET_TOPUP",
    "CAN_BE ABLE TO PURCHASE_SERVICE_WITH_WALLET",
    "CAN_UPDATE_ALL_REQUIRED_USER_DETAILS_INCLUDING_KYC",
    "CAN_DEACTIVATE_ACCOUNT",
    "CAN_REFER_SOMEONE",
    "CAN_EARN_CASHBACK_ON_REFERRAL",
  ],

  MANAGER: [
    "CAN_HAVE_WALLET_ACCOUNT_BY_DEFAULT",
    "CAN_PERFORM_TOP-UP",
    "CAN_PURCHASE_SERVICE_USING_PAYMENT_GATEWAY",
    "CAN_UPDATE_PROFILE",
    "CAN_HAVE_MULTIPLE_STORE_LOCATION",
    "CAN_GO_OFFLINE",
    "CAN_DEACTIVATE_ACCOUNT",
    "CAN_BUY_FROM_OTHER_MERCHANTS",
    "CAN_CREATE/MANAGE_AN_ORDER",
    "CAN_PROMOTE_AN_ORDER",
  ],
  
  SALESMANAGER: [
    "CAN_HAVE_WALLET_ACCOUNT_BY_DEFAULT",
    "CAN_PERFORM_TOP-UP",
    "CAN_PURCHASE_SERVICE_USING_PAYMENT_GATEWAY",
    "CAN_UPDATE_PROFILE",
    "CAN_HAVE_MULTIPLE_STORE_LOCATION",
    "CAN_GO_OFFLINE",
    "CAN_DEACTIVATE_ACCOUNT",
    "CAN_BUY_FROM_OTHER_MERCHANTS",
    "CAN_CREATE/MANAGE_AN_ORDER",
    "CAN_PROMOTE_AN_ORDER",
  ],

  SUPERADMIN: ["all"],
};
